# Generated by Django 4.2.6 on 2023-11-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_comment_fk_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.CharField(choices=[('LifeStyle', 'LifeStyle'), ('Business', 'Business'), ('Fashion', 'Fashion'), ('Travel', 'Travel')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
